# Generated by Django 5.2.3 on 2025-07-17 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='active', max_length=20, verbose_name='Template Status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('can_respond', models.BooleanField(default=True)),
                ('can_use_multiple_times', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_templates', to='users.user')),
            ],
            options={
                'verbose_name': 'Form Template',
                'verbose_name_plural': 'Form Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_email', models.EmailField(max_length=254)),
                ('responder_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('access_code', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='pending', max_length=20, verbose_name='Response Status')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formtemplate')),
            ],
            options={
                'verbose_name': 'Form Response',
                'verbose_name_plural': 'Form Responses',
            },
        ),
        migrations.CreateModel(
            name='FormTemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('restrictions', models.JSONField(default=dict)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('textarea', 'Text Area'), ('number', 'Number'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('radio', 'Radio Button'), ('dropdown', 'Dropdown'), ('file', 'File Upload')], default='checkbox', max_length=20, verbose_name='Form Type')),
                ('default_value', models.TextField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='form.formtemplate')),
            ],
            options={
                'verbose_name': 'Form Template Field',
                'verbose_name_plural': 'Form Template Fields',
            },
        ),
        migrations.CreateModel(
            name='FormFieldResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('restrictions', models.JSONField(default=dict)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('textarea', 'Text Area'), ('number', 'Number'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('radio', 'Radio Button'), ('dropdown', 'Dropdown'), ('file', 'File Upload')], default='checkbox', max_length=20, verbose_name='Form Type')),
                ('value', models.TextField(blank=True, null=True)),
                ('form_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_responses', to='form.formresponse')),
            ],
            options={
                'verbose_name': 'Form Field Response',
                'verbose_name_plural': 'Form Field Responses',
                'indexes': [models.Index(fields=['form_response'], name='form_field_response_idx')],
                'unique_together': {('form_response', 'field_name')},
            },
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['name'], name='form_template_name_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['template'], name='form_response_template_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['created_at'], name='form_response_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplatefield',
            index=models.Index(fields=['template'], name='form_template_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplatefield',
            index=models.Index(fields=['field_type'], name='form_template_field_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formtemplatefield',
            unique_together={('template', 'field_name')},
        ),
    ]
