# Generated by Django 5.2.3 on 2025-07-19 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_templates', to='users.user'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formtemplate'),
        ),
        migrations.AddField(
            model_name='formtemplatefield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='form.formtemplate'),
        ),
        migrations.AddIndex(
            model_name='formfieldresponse',
            index=models.Index(fields=['form_response'], name='form_field_response_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formfieldresponse',
            unique_together={('form_response', 'field_name')},
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['name'], name='form_template_name_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['template'], name='form_response_template_idx'),
        ),
        migrations.AddIndex(
            model_name='formresponse',
            index=models.Index(fields=['created_at'], name='form_response_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplatefield',
            index=models.Index(fields=['template'], name='form_template_idx'),
        ),
        migrations.AddIndex(
            model_name='formtemplatefield',
            index=models.Index(fields=['field_type'], name='form_template_field_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formtemplatefield',
            unique_together={('template', 'field_name')},
        ),
    ]
